/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumDeliveryRequestItemType } from "./EnumDeliveryRequestItemType";
import { PaymentUpdateManyWithoutDeliveryRequestsInput } from "./PaymentUpdateManyWithoutDeliveryRequestsInput";
import { Type } from "class-transformer";
import { EnumDeliveryRequestStatus } from "./EnumDeliveryRequestStatus";

@InputType()
class DeliveryRequestUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  customer?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  driver?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  dropoffLocation?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  itemDescription?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryRequestItemType,
  })
  @IsEnum(EnumDeliveryRequestItemType)
  @IsOptional()
  @Field(() => EnumDeliveryRequestItemType, {
    nullable: true,
  })
  itemType?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => PaymentUpdateManyWithoutDeliveryRequestsInput,
  })
  @ValidateNested()
  @Type(() => PaymentUpdateManyWithoutDeliveryRequestsInput)
  @IsOptional()
  @Field(() => PaymentUpdateManyWithoutDeliveryRequestsInput, {
    nullable: true,
  })
  payments?: PaymentUpdateManyWithoutDeliveryRequestsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  pickupLocation?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryRequestStatus,
  })
  @IsEnum(EnumDeliveryRequestStatus)
  @IsOptional()
  @Field(() => EnumDeliveryRequestStatus, {
    nullable: true,
  })
  status?: "Option1" | null;
}

export { DeliveryRequestUpdateInput as DeliveryRequestUpdateInput };
