/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { JsonFilter } from "../../util/JsonFilter";
import { StringFilter } from "../../util/StringFilter";
import { EnumDeliveryRequestItemType } from "./EnumDeliveryRequestItemType";
import { PaymentListRelationFilter } from "../../payment/base/PaymentListRelationFilter";
import { EnumDeliveryRequestStatus } from "./EnumDeliveryRequestStatus";

@InputType()
class DeliveryRequestWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  customer?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  driver?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  dropoffLocation?: JsonFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  itemDescription?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryRequestItemType,
  })
  @IsEnum(EnumDeliveryRequestItemType)
  @IsOptional()
  @Field(() => EnumDeliveryRequestItemType, {
    nullable: true,
  })
  itemType?: "Option1";

  @ApiProperty({
    required: false,
    type: () => PaymentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PaymentListRelationFilter)
  @IsOptional()
  @Field(() => PaymentListRelationFilter, {
    nullable: true,
  })
  payments?: PaymentListRelationFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  pickupLocation?: JsonFilter;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryRequestStatus,
  })
  @IsEnum(EnumDeliveryRequestStatus)
  @IsOptional()
  @Field(() => EnumDeliveryRequestStatus, {
    nullable: true,
  })
  status?: "Option1";
}

export { DeliveryRequestWhereInput as DeliveryRequestWhereInput };
