/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeliveryRequestService } from "../deliveryRequest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeliveryRequestCreateInput } from "./DeliveryRequestCreateInput";
import { DeliveryRequest } from "./DeliveryRequest";
import { DeliveryRequestFindManyArgs } from "./DeliveryRequestFindManyArgs";
import { DeliveryRequestWhereUniqueInput } from "./DeliveryRequestWhereUniqueInput";
import { DeliveryRequestUpdateInput } from "./DeliveryRequestUpdateInput";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeliveryRequestControllerBase {
  constructor(
    protected readonly service: DeliveryRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DeliveryRequest })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDeliveryRequest(
    @common.Body() data: DeliveryRequestCreateInput
  ): Promise<DeliveryRequest> {
    return await this.service.createDeliveryRequest({
      data: data,
      select: {
        createdAt: true,
        customer: true,
        driver: true,
        dropoffLocation: true,
        id: true,
        itemDescription: true,
        itemType: true,
        pickupLocation: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DeliveryRequest] })
  @ApiNestedQuery(DeliveryRequestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deliveryRequests(
    @common.Req() request: Request
  ): Promise<DeliveryRequest[]> {
    const args = plainToClass(DeliveryRequestFindManyArgs, request.query);
    return this.service.deliveryRequests({
      ...args,
      select: {
        createdAt: true,
        customer: true,
        driver: true,
        dropoffLocation: true,
        id: true,
        itemDescription: true,
        itemType: true,
        pickupLocation: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DeliveryRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deliveryRequest(
    @common.Param() params: DeliveryRequestWhereUniqueInput
  ): Promise<DeliveryRequest | null> {
    const result = await this.service.deliveryRequest({
      where: params,
      select: {
        createdAt: true,
        customer: true,
        driver: true,
        dropoffLocation: true,
        id: true,
        itemDescription: true,
        itemType: true,
        pickupLocation: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DeliveryRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDeliveryRequest(
    @common.Param() params: DeliveryRequestWhereUniqueInput,
    @common.Body() data: DeliveryRequestUpdateInput
  ): Promise<DeliveryRequest | null> {
    try {
      return await this.service.updateDeliveryRequest({
        where: params,
        data: data,
        select: {
          createdAt: true,
          customer: true,
          driver: true,
          dropoffLocation: true,
          id: true,
          itemDescription: true,
          itemType: true,
          pickupLocation: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DeliveryRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDeliveryRequest(
    @common.Param() params: DeliveryRequestWhereUniqueInput
  ): Promise<DeliveryRequest | null> {
    try {
      return await this.service.deleteDeliveryRequest({
        where: params,
        select: {
          createdAt: true,
          customer: true,
          driver: true,
          dropoffLocation: true,
          id: true,
          itemDescription: true,
          itemType: true,
          pickupLocation: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Payment",
    action: "read",
    possession: "any",
  })
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: DeliveryRequestWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        customer: true,

        deliveryRequest: {
          select: {
            id: true,
          },
        },

        id: true,
        paymentMethod: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "update",
    possession: "any",
  })
  async connectPayments(
    @common.Param() params: DeliveryRequestWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updateDeliveryRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "update",
    possession: "any",
  })
  async updatePayments(
    @common.Param() params: DeliveryRequestWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updateDeliveryRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "update",
    possession: "any",
  })
  async disconnectPayments(
    @common.Param() params: DeliveryRequestWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updateDeliveryRequest({
      where: params,
      data,
      select: { id: true },
    });
  }
}
