/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DriverInfoService } from "../driverInfo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DriverInfoCreateInput } from "./DriverInfoCreateInput";
import { DriverInfo } from "./DriverInfo";
import { DriverInfoFindManyArgs } from "./DriverInfoFindManyArgs";
import { DriverInfoWhereUniqueInput } from "./DriverInfoWhereUniqueInput";
import { DriverInfoUpdateInput } from "./DriverInfoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DriverInfoControllerBase {
  constructor(
    protected readonly service: DriverInfoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DriverInfo })
  @nestAccessControl.UseRoles({
    resource: "DriverInfo",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDriverInfo(
    @common.Body() data: DriverInfoCreateInput
  ): Promise<DriverInfo> {
    return await this.service.createDriverInfo({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        bankDetails: true,
        createdAt: true,
        id: true,
        language: true,
        preferredPostcode: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DriverInfo] })
  @ApiNestedQuery(DriverInfoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DriverInfo",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async driverInfos(@common.Req() request: Request): Promise<DriverInfo[]> {
    const args = plainToClass(DriverInfoFindManyArgs, request.query);
    return this.service.driverInfos({
      ...args,
      select: {
        bankDetails: true,
        createdAt: true,
        id: true,
        language: true,
        preferredPostcode: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DriverInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DriverInfo",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async driverInfo(
    @common.Param() params: DriverInfoWhereUniqueInput
  ): Promise<DriverInfo | null> {
    const result = await this.service.driverInfo({
      where: params,
      select: {
        bankDetails: true,
        createdAt: true,
        id: true,
        language: true,
        preferredPostcode: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DriverInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DriverInfo",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDriverInfo(
    @common.Param() params: DriverInfoWhereUniqueInput,
    @common.Body() data: DriverInfoUpdateInput
  ): Promise<DriverInfo | null> {
    try {
      return await this.service.updateDriverInfo({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          bankDetails: true,
          createdAt: true,
          id: true,
          language: true,
          preferredPostcode: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DriverInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DriverInfo",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDriverInfo(
    @common.Param() params: DriverInfoWhereUniqueInput
  ): Promise<DriverInfo | null> {
    try {
      return await this.service.deleteDriverInfo({
        where: params,
        select: {
          bankDetails: true,
          createdAt: true,
          id: true,
          language: true,
          preferredPostcode: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
